name: Reusable Release Template

on:
  workflow_call:
    inputs:
      approval_environment:
        type: string
        required: true    
    secrets:
      RELEASE_APP_ID:
        required: true
      RELEASE_APP_PRIVATE_KEY:
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      bump_type: ${{ steps.calc.outputs.bump_type }}
      new_tag: ${{ steps.calc.outputs.new_tag }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Calculate Version
        id: calc
        uses: radiusred/.github/.github/actions/calculate_version@main

  gate:
    name: Approval Checkpoint
    needs: analyze
    runs-on: ubuntu-latest
    environment: ${{ inputs.approval_environment }}
    steps:
      - run: echo "Approved."

  execute:
    needs: [analyze, gate]
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          pip install hatch
          hatch version ${{ needs.analyze.outputs.bump_type }}
          git add -A
          git commit -m "chore: release ${{ needs.analyze.outputs.new_tag }} [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
          gh release create ${{ needs.analyze.outputs.new_tag }} --generate-notes
